#! /usr/bin/expect -f

spawn git add --all
spawn git status 
spawn git commit -m "update"
spawn git push
expect "Username for 'https://github.com': "
send "blacklion11\r"
expect "Password for 'https://blacklion11@github.com': "
send "projectdev1\r"
expect eof
